### ISSUE TITLE
[New feature] Percent increase compared to the previous

### ISSUE THREAD

**Issue by JuezFenix** [EliasGrande/CerealOgameStats#3]
Hi, 

can you add a section to compare the number of previous points with the new, calculating a percentage.

Example:
Previous: 1500 points
New: 2000 points
Growth rate: 133%

**Comment by EliasGrande** [comment]
What you say already exists, not exactly as you describe it but gives the same information, using your example (from 1500 points to 2000 points) the script shows something like this:

1 » PlayerName - 2000 (+500) (+33.33%)

**Comment by JuezFenix** [comment]
Yes, but I am not referring to the previus points, I refer the previous growth statistics. In short, it's about seeing an evolution of the growth of each player basing on the previous growth (to detect slow growth for example)

Example:
Previous: 1500 points of growth 
New: 2000 points of growth 
Growth rate: 133% (positive growth)

**Comment by EliasGrande** [comment]
I see, something like:
```
Ranking by previous-new growth comparison:

1 » PlayerName / prev +500 / new +600 / diff +20%
...
```
Like I said in your other feature suggestion, I have no time right now to spend on this project, nor I'll have it in the near future, you can try to alter the script yourself or ask another scripter to do it, and send a pull request to the project with the changes

**Comment by JuezFenix** [comment]
Ok , I will try. Can you explain a few how the scrip works

**Comment by EliasGrande** [comment]
It basically compares a stored memerlist with the current one to make the statistics, the stored one is saved in the broser local storage every time the user clicks on the "Reset statistics" button.

Code in detail (by lines):

1-10: script greasemonkey metainfo
15-18: access to the ogame window
22-34: function to add css
38-68: copy member list (to avoid weird data-loss ogame does on mouseover)
72-76: script self metainfo
78-122: extend String prototype to do some basic operations
135-162: get some ogame metadata
164-201: build an object to easily work with the browser local storage to persist data
203-786: translations
788-837: output color profiles
839-852: basic score operations (compare points)
854-1423: formatter (pretify data)
1425-1762: conversor (builds statistics)
1775-2003: object to work with the DOM
2005-2095: add some css
2097-2557: Form builder (user interface)
2559-2663: Section builder (form container, user interface)
2665-2718: Interface builder (waits for some DOM objects to be available before calling the Section/Form builder)
2727-end: Script caller (waits for de DOM to be ready before start the script)

**Comment by EliasGrande** [comment]
Closing this issue because of lack of time, but I accept pull request if anyone wants to do it.
