### ISSUE TITLE
[New feature] Average growth points in sections 100.000 points

### ISSUE THREAD

**Issue by JuezFenix** [EliasGrande/CerealOgameStats#4]
Hi,

Can you add a new section in the script? Is to calculate the average increase in segment of 100,000 points 

Example:

100001-200000
Player1 - 123,564 - Average: 153 090 - Deviation from average: 29,526 (-19%)
Player2 - 179 456 - Average: 153 090 - Deviation from average: 26,366 (+ 17%)
Player3 - 156 249 - Average: 153 090 - Deviation from average: 3,159 (+ 2%)

200001-300000
...

**Comment by EliasGrande** [comment]
Hum... interesting idea, but I'm pretty busy right now in other projects to spend time in this script sorry, if you want you can edit the code yourself, or ask another scripter to do it, and send a pull request with the changes.

**Comment by EliasGrande** [comment]
Closing this issue because of lack of time, but I accept pull request if anyone wants to do it.
