### ISSUE TITLE
Script no longer working

### ISSUE THREAD

**Issue by Wraith02** [EliasGrande/CerealOgameStats#5]
Dear Cereal / Elias,
First off, thank you for the script, it has been very useful the past few years.

Unfortunately Gameforge has released some updates for the alliance page, and the script no longer works :(
http://prntscr.com/fz64dz

Is there any chance of an update to make it work again?
Thank you in advanced!
-Wraith

**Comment by Ranger2010** [comment]
HI
Same issue as Wraith02. is there a fix?
<img width="664" alt="capture d ecran 2017-07-23 a 10 45 39" src="https://user-images.githubusercontent.com/30389232/28500314-25eb13b2-6f94-11e7-8ceb-86a25421e5e2.png">

**Comment by EliasGrande** [comment]
Hi, I'm going to create a couple of accounts and try to fix it, let's see what is happening...

**Comment by EliasGrande** [comment]
I just uploaded a new version, tested on the OGame 6.4.2 http://pioneers.en.ogame.gameforge.com/ Bermuda server just now (23.07.2017 19:15:03, server time).
Please tell me if it works fine for you, and, if not, tell me your server to test it there.

**Comment by Wraith02** [comment]
It's working now!
Thank you for your quick work, much appreciated :D

**Comment by Ranger2010** [comment]
Works great again Thank you very much



Le 23 juil. 2017 à 14:16, Elías Grande Cásedas <notifications@github.com<mailto:notifications@github.com>> a écrit :


I just uploaded a new version, tested on the OGame 6.4.2 http://pioneers.en.ogame.gameforge.com/ Bermuda server just now (23.07.2017 19:15:03, server time).
Please tell me if it works fine for you, and, if not, tell me your server to test it there.

**Comment by EliasGrande** [comment]
Ok, thanks for testing, I'll close the issue now

**Comment by Ranger2010** [comment]
Very impressed on how fast you resolved the issue



Le 23 juil. 2017 à 20:02, Elías Grande Cásedas <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ok, thanks for testing, I'll close the issue now

**Comment by EliasGrande** [comment]
Every new OGame version changes a little the Alliance page layout, I already had to do this kind of fixes on previous version changes, is just a couple of tweaks on the extraction part of the script.
